<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageProjectUrl>https://github.com/tipstrade/TipsTrade.ApiClient.Core</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>A collection of interfaces, classes and extension methods that are commonly used when writing API client libraries.</Description>
		<Title>API Client abstractions and helpers.</Title>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>IDE0290</NoWarn>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="NUnit" Version="4.6.1" />
		<PackageReference Include="System.Text.Json" Version="8.0.6" />
	</ItemGroup>

	<Target Name="CopyNuGetPackageToRoot" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<ItemGroup>
			<NuPkgFiles Include="$(OutputPath)\*.nupkg" />
		</ItemGroup>
		<Copy SourceFiles="@(NuPkgFiles)" DestinationFolder="$(SolutionDir)" />
	</Target>

</Project>
